language: java

env:
  - CODACY_PROJECT_TOKEN="c2be9f43ccaf4cff9ff05739ef073a6c"

jdk:
  - openjdk14

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn verify package

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) --help