language: java

jdk:
  - openjdk11

install:
  - mvn clean compile

script:
  - mvn verify package

after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report

deploy:
  provider: heroku
  strategy: git
  api_key: $HEROKU_API_KEY
  app: app-apuntes-uniovi
  on:
    branch: master
