language: java

jdk:
  - openjdk11

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn verify package

after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report

deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: $HEROKU_API_KEY
  on:
    branch: fix-heroku
