package es.uniovi.apuntesuniovi.swagger

import org.springframework.stereotype.Controller
import org.springframework.web.bind.annotation.GetMapping

/**
 * Define swagger endpoints
 */
@Controller
class SwaggerController {

    /**
     * Redirects to the information generated by Swagger
     */
    @GetMapping("/")
    fun swagger(): String? {
        return "redirect:/swagger-ui.html"
    }
}